import { useState } from 'react';
import Head from 'next/head';

import HomePage from '../components/HomePage';
import Auth from '../components/Auth';

import styles from '../styles/Home.module.css';

export default function Home({ supabase }) {
  const [ token, setToken ] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className={styles.main}>
        { token ?  <HomePage supabase = { supabase } /> : <Auth supabase={ supabase } token = { token } setToken = { setToken } /> }
      </main>

    </div>
  )
}
